name: NodeJS with Gulp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
  node-version: "npm audit fix node-version: 
    - name: Build
      run: |
        npm install
        gulp
